msg: # MSG Options
  targetmsg: '&a%sender% -> YOU -> &r&o%msg%' # The message sent to the target
  sendermsg: '&aYOU -> %target% -> &r&o%msg%' # The message sent to the sender
  replymsg: '&a%sender% -> YOU -> &r&o%msg%' # The message sent to the target [reply]
  replysendermsg: '&aYOU -> %target% -> &r&o%msg%' # The message sent to the sender [reply]
  noargsreply: '&cYou must supply a message! Usage: /r <msg>' # No arguments [reply]
  notonlinereply: '&cYou have no one to reply too!' # Not online [reply]
  noargsmsg: '&cYou must supply a player name and message! Usage: /msg <player> <msg>' # No args [msg]
  notonlinemsg: '&cThat player is not online! Usage: /msg <player> <msg>' # Not online [msg]
  sendingtoself: '&cYou cannot message yourself silly! Usage: /msg <player> <msg>' # Sending to self
use-staff-chat: true # Use the staff chat. [true or false]
use-staff-chat-actionbar: true # Use the staff chat actionbar. [true or false]
staff-chat-not-enabled: '&fUnknown command. Type "/help" for help.' # If the above is set to false then when the user exucutes /sc show them this.
staffchat: # Staffchat options
  enabled: '&c&l[&r&fSC&c&l]&r&7 StaffChat has been enabled!' # SC enabled
  disabled: '&c&l[&r&fSC&c&l]&r&7 StaffChat has been disabled!' # SC disabled
  format: '&c&l[&r&fSC&c&l]&r&7 %player%&b:&f %msg%' # SC format
  actionbar-format: '&c%player%:&f %msg%' # The actionbar format if use-staff-chat-actionbar is true.
chat: # Chat options
  disabled: '&c&lChat was disabled by %sender%!' # Chat disabled
  enabled: '&c&lChat was enabled by %sender%!' # Chat enabled
  clearchat-message-noargs: '&c%sender% has cleared the chat.' # No reason was given
  clearchat-message: '&c%sender% has cleared the chat for %reason%'
json: # JSON options
  use-welcome-message: false # Use the welcome message (true or false)
  json-welcome: '&cWelcome to our server %player%!' # When the player joins they recieve this message
  json-hover: '&cClick here to execute a command!' # When the player hovers over the message show this message
  json-command: '/mhelp' # The suggested command to run when they click the message
death: # Death message settings
  use: true # Use the custom death message
  death-message: '&e%player% &cwas killed by &e%killer%&c!' # The death message if above is true
voting:
  header: '&f===================' # Voting header
  links: # Voting links
    - '&chttp://muricans.ml'
  footer: '&f===================' # Voting footer
replacechat: # ReplaceChat messages etc.
  invalid-usage: '&cInvalid usage! /replacechat <player>' # No arguments found.
  toggled-on: '&aReplaceChat toggled on for %target%' # Toggled on
  toggled-off: '&cReplaceChat toggled off for %target%' # Toggled off
  offline-player: '&c%target% is offline! Try a different player.' # Target is offline
  words: # On chat if the player is being replacechatted by somebody replace whatever they say with these words. (Randomly)
    - 'I like to eat cookies, they''re bad for health though :('
    - 'I''m a dumb person, please ban me!'
    - 'This server is using MSG, download it @ https://www.spigotmc.org/resources/msg-tested-on-1-8-1-7-10-1-10.31708/'
    - 'Thanks for using MSG, please drop a rating if you liked it!'
    - 'a'
    - 'b'
    - 'c'
    - 'd'
    - 'e'
    - 'f'
tab: # !ProtocolLib needed!
  cancel: true # 1.8-1.10 only.
  first-param-only: true # If the player adds more than 1 argument stop blocking it so they can tab complete player names etc.
  use-message: true # If the above is true do you want to send a message to the player when they do it?
  message: '&cPlease don''t try to steal our commands!' # If the above is true send them this message.
profanity:
  enable: true
  block: true
  alert: '&c%player%: &f%msg%'
  warn-message: '&aPlease do not swear on our server, all staff have been alerted.'
  blacklist:
  - 'fuck'
  - 'pussy'
  - 'dick'
  - 'vagina'
  - 'penis'
  - 'fag'
  - 'hitler'
  - 'nazi'
  - 'kkk'
  - 'nigger'
  - 'faggot'
  - 'nigga'
  - 'bitch'
  - 'ass'
  whitelist:
  - 'glass'
  - 'mass'
  - 'bass'
command-blocking:
  enable: true
  alert: true
  warn-message: '&aThat command is blocked, sorry.'
  alert-message: '&c%player%: &f%msg%'
  blacklist:
  - 'plugins'
  - 'pl'
  - '?'
  - 'bukkit:help'
staff:
  header: '&e==================='
  group: '&c- %group%'
  footer: '&e==================='
sounds:
  enable: true
  soundToPlay: LEVEL_UP
  toggled:
    on: '&aSounds toggled on.'
    off: '&cSounds toggled off.'