name: MSG
version: 2.4
softdepend: [ProtocolLib]
main: me.jdog.msg.Main
author: Muricans
commands:
  sounds:
    permission: msg.togglesounds
    permission-message: §cNo permission.
  staffhide:
  staff:
    permission: msg.staff
    permission-message: §cNo permission.
  stafflist:
    permission: msg.stafflist
    permission-message: §cNo permission.
  clearchat:
    aliases: [cc]
    usage: /<command> [reason]
    permission: msg.clearchat
    permission-message: §cNo permission.
  profanity:
    permission: msg.profanity
    permission-message: §cNo permission.
    usage: /<command> <args>
    aliases: [prof]
  replacechat:
    permission: msg.replacechat
    permission-message: §cNo permission.
    usage: /<command> <player>
    aliases: [rchat]
  vote:
    usage: /<command>
    permission: msg.vote
    permission-message: §cNo permission.
  msg:
    usage: /<command> <player> <args>
    permission: msg.msg
    permission-message: §cNo permission.
    aliases: [m, t, tell]
    description: Message a player.
  reply:
    usage: /<command> <args>
    permission: msg.reply
    permission-message: §cNo permission.
    aliases: [r]
    description: Reply to your last message.
  message:
    usage: /<command> <args>
    permission: msg.message
    permission-message: §cNo permission.
    description: Message plugin command.
    aliases: [msgplug, msgplugin]
  mhelp:
    usage: /<command>
    permission-message: §cNo permission.
    description: Message help.
  staffchat:
    usage: /<command> [msg]
    description: Enter staffchat mode.
    permission: msg.staffchat
    permission-message: §cNo permission.
    aliases: [sc]
  moptions:
    usage: /<command> <args>
    description: Options for the MSG plugin.
    permission: msg.options
    permission-message: §cNo permission.
    aliases: [mo]
  mpanel:
    usage: /<command>
    description: Options as gui form.
    permission: msg.options.gui
    permission-message: §cNo permission.
    aliases: [mp]
  togglechat:
    usage: /<command>
    description: Mute the chat.
    permission: msg.chat.toggle
    permission-message: §cNo permission.
    aliases: [tc, tchat]
permissions:
  msg.staffchat.*:
    description: All staffchat permissions.
    default: op
    children:
      msg.staffchat.see: true
      msg.staffchat.actionbar: true
      msg.staffchat: true
  msg.chat.*:
    description: All chat commands.
    default: op
    children:
      msg.chat.toggle: true
      msg.chat.talk: true
  msg.chat.talk:
    description: Talk when chat is muted.
    default: op
  msg.options.*:
    description: All option commands.
    default: op
    children:
      msg.options: true
      msg.options.gui: true
  msg.user:
    description: User commands.
    default: true
    children:
      msg.msg: true
      msg.reply: true
      msg.vote: true
      msg.rules: true
      msg.staff: true
      msg.togglesounds: true
  msg.help:
    description: Help for message permission.
    default: true
  msg.staffchat.see:
    description: See the staffchat.
    default: op
  msg.staffchat.actionbar:
    description: See an actionbar if the config value for it is true.
    default: op
  msg.sign.create:
    description: Create MSG signs
    default: op
  msg.sign.interact:
    description: Interact with MSG signs
    default: op
  msg.sign.*:
    description: All MSG sign permissions.
    default: op
    children:
      msg.sign.create: true
      msg.sign.interact: true
  msg.tab:
    description: Bypass the antitab system
    default: op
  msg.profanity.bypass:
    description: Bypass the antiswear system
    default: op
  msg.profanity.alert:
    description: Recieve alerts when people swear
    default: op
  msg.profanity.*:
    description: All Profanity permissions.
    default: op
    children:
      msg.profanity.bypass: true
      msg.profanity.alert: true
      msg.profanity: true
      msg.profanity.lookup: true
      msg.profanity.whitelist: true
      msg.profanity.blacklist: true
  msg.profanity.blacklist:
    default: op
    description: Blacklist words from in-game
  msg.profanity.whitelist:
    default: op
    description: Whitelist words from in-game
  msg.clearchat.reason:
    description: Give a reason when clearing the chat
    default: op
  msg.clearchat.*:
    description: All clearchat permissions
    default: op
    children:
      msg.clearchat.reason: true
      msg.clearchat: true
  msg.command-blocking.bypass:
    default: op
  msg.command-blocking.alert:
    default: op
  msg.command-blocking.*:
    default: op
    description: All command-blocking permissions.
    children:
      msg.command-blocking.bypass: true
      msg.command-blocking.alert: true