msg: # MSG Options
  targetmsg: '&a%sender% -> YOU -> &r&o%msg%' # The message sent to the target
  sendermsg: '&aYOU -> %target% -> &r&o%msg%' # The message sent to the sender
  replymsg: '&a%sender% -> YOU -> &r&o%msg%' # The message sent to the target [reply]
  replysendermsg: '&aYOU -> %target% -> &r&o%msg%' # The message sent to the sender [reply]
  noargsreply: '&cYou must supply a message! Usage: /r <msg>' # No arguments [reply]
  notonlinereply: '&cYou have no one to reply too!' # Not online [reply]
  noargsmsg: '&cYou must supply a player name and message! Usage: /msg <player> <msg>' # No args [msg]
  notonlinemsg: '&cThat player is not online! Usage: /msg <player> <msg>' # Not online [msg]
  sendingtoself: '&cYou cannot message yourself silly! Usage: /msg <player> <msg>' # Sending to self
use-staff-chat: true # Use the staff chat. [true or false]
use-staff-chat-actionbar: true # Use the staff chat actionbar. [true or false]
staff-chat-not-enabled: '&fUnknown command. Type "/help" for help.' # If the above is set to false then when the user exucutes /sc show them this.
staffchat: # Staffchat options
  enabled: '&c&l[&r&fSC&c&l]&r&7 StaffChat has been enabled!' # SC enabled
  disabled: '&c&l[&r&fSC&c&l]&r&7 StaffChat has been disabled!' # SC disabled
  format: '&c&l[&r&fSC&c&l]&r&7 %player%&b:&f %msg%' # SC format
  actionbar-format: '&c%player%:&f %msg%' # The actionbar format if use-staff-chat-actionbar is true.
chat: # Chat options
  disabled: '&c&lChat was disabled by %sender%!' # Chat disabled
  enabled: '&c&lChat was enabled by %sender%!' # Chat enabled
json: # JSON options
  use-welcome-message: false # Use the welcome message (true or false)
  json-welcome: '&cWelcome to our server %player%!' # When the player joins they recieve this message
  json-hover: '&cClick here to execute a command!' # When the player hovers over the message show this message
  json-command: '/mhelp' # The suggested command to run when they click the message
death: # Death message settings
  use: true # Use the custom death message
  death-message: '&e%player% &cwas killed by &e%killer%&c!' # The death message if above is true
voting:
  header: '&f===================' # Voting header
  links: # Voting links
    - '&chttp://muricans.ml'
  footer: '&f===================' # Voting footer